# Generated by Django 3.2.10 on 2022-01-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medseer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='organization',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='medseer.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='medseer.Author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='medseer.journal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(blank=True, default='', upload_to='pdfs/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='tei',
            field=models.FileField(blank=True, default='', upload_to='xmls/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
