# Generated by Django 3.2.10 on 2022-01-25 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medseer', '0002_auto_20220126_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medseer.organization'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medseer.journal'),
        ),
    ]
