# Generated by Django 3.2.10 on 2022-01-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medseer', '0003_auto_20220126_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
