# Generated by Django 4.0.1 on 2022-01-31 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medseer', '0004_alter_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload *.pdf file and Save to generate .tie.xml using Grobid', upload_to='pdfs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tei',
            field=models.FileField(blank=True, help_text='Upload *.tie.xml file and Save to autofill paper data', upload_to='xmls/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
    ]
