# Generated by Django 4.0.1 on 2022-01-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medseer', '0005_paper_published_at_alter_paper_pdf_alter_paper_tei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
